package DCMS_CORBA;


/**
* DCMS_CORBA/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS_CORBA.idl
* Wednesday, August 2, 2017 8:41:05 o'clock PM EDT
*/

public interface DCMSOperations 
{
  String createTRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerId, String firstName, String lastName, String courseRegistered, String status, String statusDate);
  String getRecordCounts (String managerId);
  String editRecord (String managerId, String recordID, String fieldName, String newValue);
  String transferRecord (String managerId, String recordID, String remoteCenterServerName);
} // interface DCMSOperations
