package DCMS_CORBA;


/**
* DCMS_CORBA/DCMSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS_CORBA.idl
* Wednesday, August 2, 2017 8:41:05 o'clock PM EDT
*/

abstract public class DCMSHelper
{
  private static String  _id = "IDL:DCMS_CORBA/DCMS:1.0";

  public static void insert (org.omg.CORBA.Any a, DCMS_CORBA.DCMS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DCMS_CORBA.DCMS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DCMS_CORBA.DCMSHelper.id (), "DCMS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DCMS_CORBA.DCMS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DCMSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DCMS_CORBA.DCMS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DCMS_CORBA.DCMS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCMS_CORBA.DCMS)
      return (DCMS_CORBA.DCMS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCMS_CORBA._DCMSStub stub = new DCMS_CORBA._DCMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DCMS_CORBA.DCMS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCMS_CORBA.DCMS)
      return (DCMS_CORBA.DCMS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCMS_CORBA._DCMSStub stub = new DCMS_CORBA._DCMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
