package DCMS_CORBA;


/**
* DCMS_CORBA/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS_CORBA.idl
* Wednesday, August 2, 2017 8:41:05 o'clock PM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
